### ISSUE TITLE
Cart is only submitted for authorization

### ISSUE THREAD

**Issue by fjbender** [PAYONE-GmbH/prestashop-16#11]
In fcpayone/Core/Request/Builder/Payment/Base.php `setItemsToRequest()` is only executed when the request is authorization. This is not intentional.

**Comment by paeddl** [comment]
@fjbender So the basket should always be sent as soon as `sendBasketContent()` is set / returning true, right?

**Comment by fjbender** [comment]
@paeddl Correct.

**Comment by fjbender** [comment]
Fixed with #13
