### ISSUE TITLE
adminorder lost formating when payone is activated

### ISSUE THREAD

**Issue by becoda** [PAYONE-GmbH/prestashop-16#8]
I tryed that also on a fresh downloaded 1.6.1.15, also get the same error 

index.php:283 Uncaught ReferenceError: $ is not defined
    at index.php:283
index.php?controller=AdminOrders&id_order=12124&vieworder&token=e0458ee…:283 Uncaught ReferenceError: $ is not defined
    at index.php?controller=AdminOrders&id_order=12124&vieworder&token=e0458ee…:283

thx in advance

simply: head> is empty in adminorder section, therefore no css

**Comment by fjbender** [comment]
Thanks for your input, we'll look into that.

**Comment by hreinberger** [comment]
can't reproduce in current master, so this seems fixed
